update for script 1.5

diff --git a/scripts/nagios_hpeilo_cfg_generator.in b/scripts/nagios_hpeilo_cfg_generator.in
--- a/scripts/nagios_hpeilo_cfg_generator.in
+++ b/scripts/nagios_hpeilo_cfg_generator.in
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
-# nagios_hpilo_cfg_generator -- The script aims to automatically generate
+# nagios_hpeilo_cfg_generator -- The script aims to automatically generate
 #				nagios configuration once discovering the
-#				HP ProLiant Servers. 
-#  (C) Copyright [2015] Hewlett-Packard Development Company, L.P.
+#				HPE ProLiant Servers. 
+#  (C) Copyright [2015] Hewlett Packard Enterprise Development Company, L.P.
 #
 #  This program is free software; you can redistribute it and/or modify 
 #  it under the terms of version 2 of the GNU General Public License as 
@@ -26,15 +26,17 @@
 prefix=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
 NagiosLibexec="${prefix}"
-NagiosHpiloEngine="nagios_hpilo_engine"
-
+NagiosHpiloEngine="nagios_hpeilo_engine"
+NagiosHpHltStatusHnd="nagios_hpeilo_health_service"
+NagiosHpTrapCmd="nagios_hpeilo_traps"
 HpiloXmlFile="/tmp/ilo_xml_content.xml"
-HpiloXmlTag=(SPN PN)
-HpiloHostgroup="hpilo-servers"
+HpiloXmlTag=(SPN PN UUID)
+HpiloHostgroup="hpeilo-servers"
 HpiloProductOid="1.3.6.1.4.1.232.2.2.4.2"
-HpiloLogFile="/var/log/nagios_hpilo_cfg_generator.log"
-HpiloSnmpComm="public" # hpilo ilo community string
+HpiloLogFile="/var/log/nagios_hpeilo_cfg_generator.log"
+HpiloSnmpComm="public" # hpeilo ilo community string
 HpiloServices=("System Status" "Fans" "Memory" "Network" "Power Supplies" "Processors" "Storage" "Temperatures")
+HpiloServiceGroup="servicegroup_name"
 
 CheckInterval=5 # 5-minute interval
 MaxAttempts=10
@@ -47,7 +49,7 @@ ConfigDisc=3
 
 DiscModes=($ActiveDisc $PassiveDisc $ConfigDisc)
 
-LockFile="/tmp/nagios_hpilo.lock"
+LockFile="/tmp/nagios_hpeilo.lock"
 TmpFile="/tmp/tmp.txt"
 
 # SNMP variables
@@ -66,12 +68,13 @@ NmapScanReportStr="Nmap scan report for"
 
 #snmptrapd configuration definitions
 SNMPTRAPD_AUTH_COMM="authCommunity log,execute,net public"
-HPILO_CFG_GEN="nagios_hpilo_cfg_generator"
-HPILO_TRAPS="nagios_hpilo_traps"
+HPILO_CFG_GEN="nagios_hpeilo_cfg_generator"
+HPILO_TRAPS="nagios_hpeilo_traps"
 #NAGIOS_ILO_CONFIG_FILE="hpiLO_nagios_plugin.cfg"
 SNMPTRAPD_AUTH="authCommunity log,execute,net"
 
 # Find the path
+NAGIOS_ILO_PLUGINS_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 NAGIOS_INST_PATH="${prefix}"
 SNMPTRAPD_CONF=`find /etc  -name snmptrapd.conf`
 #NAGIOS_ILO_CONFIG_PATH=`find /usr/local/ -name $NAGIOS_ILO_CONFIG_FILE | xargs dirname`
@@ -217,10 +220,33 @@ do
 	HostGroup[$host_group_entries]=`echo $line | awk -F , '{print $1}'`
 
 	# Get the IP address or Subnet
-	#	IPAddrGroup[$host_group_entries]=`echo $line | awk -F , '{print $2}'`
 	HostGroupIPAddr[$host_group_entries]=`echo $line | awk -F , '{print $2}'`
 
 	host_group_entries=$(($host_group_entries+1))
+
+done < "$HostGroupCfgFile"
+}
+
+#Read contact group
+function read_contact_group() {
+local	contact_group_entries=0
+
+while read line
+do
+	# ignore the space line
+	if [ "x${line}" = "x" ]; then
+		continue
+	fi
+
+	# ignore the comment lines
+	if [ "x$(echo $line | grep -E \"^#\")" != "x" ]; then
+		continue
+	fi
+
+	# Get the name of the host group
+	contact_name[$contact_group_entries]=`echo $line | awk -F , '{print $1}'`
+
+	contact_group_entries=$(($contact_group_entries+1))
 
 done < "$HostGroupCfgFile"
 }
@@ -230,6 +256,7 @@ done < "$HostGroupCfgFile"
 function read_config_file() {
 local temp=
 local host_group_entries=
+local contact_entries=
 
 if [ $mode -eq 2 ] && [ $cfg_file -eq 1 ]; then
 	echo
@@ -244,12 +271,9 @@ do
 	fi
 	# ignore the comment lines
 	if [ "x$(echo $line | grep -E "^#")" != "x" ]; then
-		#                       echo "comment line"
 		continue
 	fi
 	config_type=`echo $line | awk '{print $1}'`
-	#echo $config_type
-	#       echo
 	case "$config_type" in
 		PASSIVE_DISCOVERY)
 		passive_disc=`echo $line | awk '{print $2}'`
@@ -277,9 +301,25 @@ do
 		CHECK_INTERVAL)
 		CheckInterval=`echo $line | awk '{print $2}'`
 		;;
-
+		NAGIOS_HOSTIP)
+		NAGIOS_HOSTIP=`echo $line | awk '{print $2}'`
+		;;
+                CONTACT:)
+                contemp=`echo $line | awk -F: '{print $2}'`
+		contact_entries=${#contact_name[@]}
+		# Get the name of the contacts
+		contact_name[$contact_entries]=`echo $contemp | awk -F , '{print $1}'`
+		contact_alias[$contact_entries]=`echo $contemp | awk -F , '{print $2}'`
+		contact_mail_id[$contact_entries]=`echo $contemp | awk -F , '{print $3}'`
+                ;;		
+		CONTACTGROUP:)
+                conGtemp=`echo $line | awk -F: '{print $2}'`
+                contactgrp_entries=${#ContactgrpInfo[@]}
+		# Get the name of the contact group
+		contact_grp_name[contactgrp_entries]=`echo $conGtemp | awk -F , '{print $1}'`
+		contact_grp_alias[contactgrp_entries]=`echo $conGtemp | awk -F , '{print $2}'`
+		;;		
 		*)
-		#echo "not identified config value $line"
 		;;
 	esac
 done <  "$HostGroupCfgFile"
@@ -474,19 +514,19 @@ echo -ne "Progress: $(($1*100/$2))% (scanned $1 of $2 hosts)\r"
 # 161/udp open  snmp
 # | snmp-sysdescr: Integrated Lights-Out 4 1.30 Mar 18 2013
 # |_  System uptime: 40 days, 11:15:49.94 (349654994 timeticks)
-# MAC Address: 9C:8E:99:6E:0C:FA (Hewlett-Packard Company)
+# MAC Address: 9C:8E:99:6E:0C:FA (Hewlett-Packard Enterprise Company)
 #
 # Nmap scan report for 16.153.113.7
 # Host is up (0.00015s latency).
 # PORT    STATE  SERVICE
 # 161/udp closed snmp
-# MAC Address: 98:4B:E1:04:F8:7E (Hewlett-Packard Company)
+# MAC Address: 98:4B:E1:04:F8:7E (Hewlett-Packard Enterprise Company)
 #
 # Nmap scan report for 16.153.113.8
 # Host is up (0.00011s latency).
 # PORT    STATE         SERVICE
 # 161/udp open|filtered snmp
-# MAC Address: 3C:D9:2B:08:95:92 (Hewlett-Packard Company)
+# MAC Address: 3C:D9:2B:08:95:92 (Hewlett-Packard Enterprise Company)
 # ............................................
 # ............................................
 ##############################################################
@@ -551,7 +591,7 @@ if [ -f $1 ]; then
 	str=`grep "$2" $1`
 fi	
 
-echo $str
+echo -e "$str"
 }
 
 # argument 1 ($1): The data to be logged
@@ -571,7 +611,11 @@ function write_nagios_generic_host_section() {
 	echo -e "\tmax_check_attempts $MaxAttempts"     >> $NagiosIloCfgFile
 	echo -e "\tcheck_command check-iLO-host-alive"  >> $NagiosIloCfgFile
 	echo -e "\taction_url https://\$HOSTADDRESS$"	>> $NagiosIloCfgFile
-	echo -e "\ticon_image_alt HP Integrated Lights-Out (iLO)" >> $NagiosIloCfgFile
+	echo -e "\t_nagiosip	$NAGIOS_HOSTIP"		>> $NagiosIloCfgFile
+	echo -e "\ticon_image_alt HPE Integrated Lights-Out (iLO)" >> $NagiosIloCfgFile
+	if [ "x${contact_grp_name}" != "x" ]; then	
+		echo -e "\tcontact_groups $contact_grp_name"                          >> $NagiosIloCfgFile
+	fi
 	echo -e "\tregister 0"     			>> $NagiosIloCfgFile
 	echo -e "}\n"					>> $NagiosIloCfgFile
 }
@@ -581,6 +625,7 @@ function write_nagios_host_section() {
 echo -e "define host {"				>> $NagiosIloCfgFile
 echo -e "\thost_name ${IloXmlTag[0]}"		>> $NagiosIloCfgFile
 echo -e "\taddress $1"				>> $NagiosIloCfgFile
+echo -e "\t_UUID ${IloXmlTag[2]}"               >> $NagiosIloCfgFile
 echo -e "\t_iLO_SNMP_community $2"		>> $NagiosIloCfgFile
 echo -e "\tuse generic-iLO-host"		>> $NagiosIloCfgFile
 echo -e "}\n"					>> $NagiosIloCfgFile
@@ -597,6 +642,12 @@ echo -e "define command {"			>> $NagiosIloCfgFile
 echo -e "\tcommand_name check-iLO-host-alive"	>> $NagiosIloCfgFile
 echo -e "\tcommand_line $NagiosLibexec/$NagiosHpiloEngine -H \$HOSTADDRESS\$ -C  \$_HOSTILO_SNMP_COMMUNITY\$ -o 11"			>> $NagiosIloCfgFile
 echo -e	"}\n"					>> $NagiosIloCfgFile
+
+echo -e "define command {"			>> $NagiosIloCfgFile
+echo -e "\tcommand_name $NagiosHpHltStatusHnd"	>> $NagiosIloCfgFile
+echo -e "\tcommand_line $NagiosLibexec/$NagiosHpTrapCmd -A -H \$HOSTADDRESS\$ -C  \$_HOSTILO_SNMP_COMMUNITY\$ -o \$ARG1\$"			>> $NagiosIloCfgFile
+echo -e	"}\n"					>> $NagiosIloCfgFile
+
 }
 
 #write generic services to ilo config file
@@ -605,8 +656,22 @@ function write_nagios_genric_service_section ()
 	echo -e "define service {"             		 >> $NagiosIloCfgFile
 	echo -e "\tname generic-iLO-service"             >> $NagiosIloCfgFile
 	echo -e "\tuse generic-service"             	 >> $NagiosIloCfgFile
+	echo -e "\tpassive_checks_enabled	1" 	 >> $NagiosIloCfgFile
+	echo -e "\tactive_checks_enabled	1" 	 >> $NagiosIloCfgFile
 	echo -e "\tcheck_interval $CheckInterval"	 >> $NagiosIloCfgFile
-#	echo -e "\taction_url https://\$HOSTADDRESS$"	 >> $NagiosIloCfgFile
+	echo -e "\tregister 0"                           >> $NagiosIloCfgFile
+	echo -e "}\n"                          		 >> $NagiosIloCfgFile
+
+	echo -e "define service {"             		 >> $NagiosIloCfgFile
+	echo -e "\tname generic-iLO-Passive-service"     >> $NagiosIloCfgFile
+	echo -e "\tuse generic-service"             	 >> $NagiosIloCfgFile
+	echo -e "\tpassive_checks_enabled	1" 	 >> $NagiosIloCfgFile
+	echo -e "\tactive_checks_enabled	1" 	 >> $NagiosIloCfgFile
+	echo -e "\tcheck_period	24x7"       >> $NagiosIloCfgFile
+	echo -e "\tcheck_interval 2880"        >> $NagiosIloCfgFile
+	echo -e "\tnormal_check_interval 2880"        >> $NagiosIloCfgFile
+	echo -e "\tcheck_freshness                 1"              >> $NagiosIloCfgFile
+	echo -e "\tfreshness_threshold		10800"              >> $NagiosIloCfgFile
 	echo -e "\tregister 0"                           >> $NagiosIloCfgFile
 	echo -e "}\n"                          		 >> $NagiosIloCfgFile
 }
@@ -616,13 +681,42 @@ local	idx=0
 
 for((idx=0;idx<${#HpiloServices[@]};idx++)); do
 	echo -e "define service {"		>> $NagiosIloCfgFile
-	echo -e "\tuse generic-iLO-service"	>> $NagiosIloCfgFile
+	if [ $idx != 0 ]; then
+		echo -e "\tuse generic-iLO-Passive-service"  >> $NagiosIloCfgFile
+	else
+		echo -e "\tuse generic-iLO-service"	>> $NagiosIloCfgFile
+	fi
 	echo -e "\thostgroup_name $1" 		>> $NagiosIloCfgFile
-	echo -e "\tservice_description ${HpiloServices[$idx]}" \
-	>> $NagiosIloCfgFile
+	echo -e "\tservice_description ${HpiloServices[$idx]}" >> $NagiosIloCfgFile
 
-	echo -e "\tcheck_command $NagiosHpiloEngine!$(($idx+1))" \
-	>> $NagiosIloCfgFile
+	case "$idx" in
+	   1)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx+1))" >> $NagiosIloCfgFile
+		;;
+	   2)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx+3))" >> $NagiosIloCfgFile
+		;;
+	   3)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx+4))" >> $NagiosIloCfgFile
+		;;
+	   4)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx-3))" >> $NagiosIloCfgFile
+		;;
+	   5)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx+1))" >> $NagiosIloCfgFile
+		;;
+	   6)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx-2))" >> $NagiosIloCfgFile
+		;;
+	   7)
+        	echo -e "\taction_url  http://\$_HOSTNAGIOSIP$/$NagiosService/hpeilo/nagios_hpeilo_service_details.php?ip=\$HOSTADDRESS$&comm=\$_HOSTILO_SNMP_COMMUNITY$&id=$(($idx-4))" >> $NagiosIloCfgFile
+		;;
+	   *)
+		;;
+	esac
+
+	echo -e "\tcheck_command $NagiosHpHltStatusHnd!$(($idx+1))" >> $NagiosIloCfgFile
+
 	echo -e	"}\n"				>> $NagiosIloCfgFile
 done
 }
@@ -635,22 +729,61 @@ echo -e "\tmembers ${IloXmlTag[0]}"		>> $NagiosIloCfgFile
 echo -e "}\n"					>> $NagiosIloCfgFile
 }
 
+# $1: Service Group
+function write_nagios_servicegroup_section () {
+
+for((idx=0;idx<${#HpiloServices[@]};idx++)); do
+	echo -e "define servicegroup {"					>> $NagiosIloCfgFile
+	echo -e "\t$1\t${HpiloServices[$idx]}"				>> $NagiosIloCfgFile
+	echo -e "\tmembers \t${IloXmlTag[0]},${HpiloServices[$idx]}"     >> $NagiosIloCfgFile
+	echo -e "}\n"                                          		>> $NagiosIloCfgFile
+done
+}
+
+function write_nagios_contact_section() {
+for((idx=0;idx<${#contact_name[@]};idx++)); do
+	echo -e "define contact {"                         >> $NagiosIloCfgFile
+	echo -e "\tcontact_name\t${contact_name[$idx]}"           >> $NagiosIloCfgFile
+	echo -e "\talias\t${contact_alias[$idx]}"                          >> $NagiosIloCfgFile
+	echo -e "\temail\t${contact_mail_id[$idx]}"               >> $NagiosIloCfgFile
+	echo -e "\tuse generic-contact"                >> $NagiosIloCfgFile
+	echo -e "}\n"                                   >> $NagiosIloCfgFile
+done
+}
+
+function write_nagios_contact_group_section() {
+	echo -e "define contactgroup {"                         >> $NagiosIloCfgFile
+	echo -e "\tcontactgroup_name $contact_grp_name"           >> $NagiosIloCfgFile
+	echo -e "\talias $contact_grp_alias"                          >> $NagiosIloCfgFile
+	for((idx=0;idx<${#contact_name[@]};idx++)); do
+        	if [ "$idx" -eq "0" ]; then
+               		memberContacts=${contact_name[$idx]}
+        	else
+                	memberContacts="$memberContacts,${contact_name[$idx]}"
+        	fi
+	done
+	echo -e "\tmembers $memberContacts"               >> $NagiosIloCfgFile
+	echo -e "}\n"                                   >> $NagiosIloCfgFile
+}
+
+
 # $1: IP address
 function check_ilo_device() {
-local	has_configured=
-local	product_str=
+local	has_IP_configured=
+local   has_UUID=
+local	UUID_str=
 
 
 get_xml_content $1
 
-# Check if the device is BMC (HP iLO)
+# Check if the device is BMC (HPE iLO)
 if [[ ${IloXmlTag[1]} != *iLO* ]]; then
-	write_log "The host '$1' is not a HP iLO device"
+	write_log "The host '$1' is not a HPE iLO device"
 	return 1
 fi
 
 if [[ ${IloXmlTag[0]} != *ProLiant* ]]; then
-	write_log "The host '$1' is not a HP ProLiant server"
+	write_log "The host '$1' is not a HPE ProLiant server"
 	return 1
 fi
 # Check if device is Gen8 and above 
@@ -662,9 +795,27 @@ fi
 write_log "The product string of the IP '$1' is '${IloXmlTag[0]}'."
 
 write_log "Nagios config file $NagiosIloCfgFile"
-has_configured=$(search_string $NagiosIloCfgFile "$1")
+has_IP_configured=$(search_string $NagiosIloCfgFile "$1")
 
-if [ "x${has_configured}" != "x" ]; then
+UUID_str=${IloXmlTag[2]}
+if [ "$UUID_str" != "000" ]; then
+	has_UUID=$(search_string $NagiosIloCfgFile "$UUID_str")
+	if [ "x$has_UUID" != "x" ]; then
+		ip_line=`grep -n -B 1 "$has_UUID" $NagiosIloCfgFile | grep "address" | head -n 1`
+		s_ip=`echo $ip_line |awk -F ' ' '{print $3}'`
+		if [ "$1" = "$s_ip" ]; then
+			write_log "The IP '$1' has been configured"
+			return 1
+		else
+			#update the new IP address
+			write_log "The IP $1 has changed to IP $s_ip"
+			ip_line=`echo $ip_line |awk -F '-' '{print $1}'`
+			sed -i "${ip_line}s/$s_ip/$1/" $NagiosIloCfgFile
+			return 1
+		fi
+
+	fi
+elif [ "x${has_IP_configured}" != "x" ]; then
 	write_log "The IP '$1' has been configured"
 	return 1
 fi
@@ -696,7 +847,7 @@ fi
 
 
 # Find the number of existed servers in NagiosIloCfgFile
-num_srvs_exist=`echo $(search_string $NagiosIloCfgFile "${IloXmlTag[0]}") | grep "host_name" | wc -l `
+num_srvs_exist=`echo -e "$(search_string $NagiosIloCfgFile "${IloXmlTag[0]}")" | grep "host_name" | wc -l `
 
 IloXmlTag[0]=${IloXmlTag[0]}-$(($num_srvs_exist+1))
 
@@ -748,6 +899,20 @@ else
 	sed -i "$s_line s/\$/, ${IloXmlTag[0]}/" $NagiosIloCfgFile
 fi
 
+#Find the specific service group
+if [ "x$(cat $NagiosIloCfgFile | grep "$HpiloServiceGroup")" = "x" ]; then
+	#The specific service group is not created yet.
+	write_nagios_servicegroup_section "$HpiloServiceGroup" 
+else 
+	#Add host to specific service group
+
+	for((id=0;id<${#HpiloServices[@]};id++)); do
+		s_line=`grep -n "servicegroup_name" $NagiosIloCfgFile  | grep "${HpiloServices[$id]}" |  head -n 1 | awk -F ':' '{print $1}'`
+		s_line=$(($s_line+1))
+		sed -i "$s_line s/\$/, ${IloXmlTag[0]},${HpiloServices[$id]}/" $NagiosIloCfgFile
+	done
+fi
+
 services_configured=`grep -c -w "service_description" $NagiosIloCfgFile`
 if [ $services_configured -ne 8 ]; then
 	write_nagios_services_section "$host_group"
@@ -768,6 +933,22 @@ command_configured=$(search_string $NagiosIloCfgFile "command_name")
 
 if [ "x${command_configured}" = "x" ]; then
 	write_nagios_command_section
+fi
+
+contact_configured=$(search_string $NagiosIloCfgFile "contact_name")
+
+if [ "x${contact_configured}" = "x" ]; then
+	if [ "x${contact_name}" != "x" ]; then		
+		write_nagios_contact_section
+	fi
+fi
+
+contactgrp_configured=$(search_string $NagiosIloCfgFile "contactgroup_name")
+
+if [ "x${contactgrp_configured}" = "x" ]; then
+	if [ "x${contact_grp_name}" != "x" ]; then
+        	write_nagios_contact_group_section
+	fi
 fi
 
 rm -f $LockFile
@@ -1143,6 +1324,12 @@ fi
 
 local nagios_path=`dirname $nagios_cfg`
 
+#check hpeilo folder in nagios installation directory
+if [ -d "$NAGIOS_ILO_PLUGINS_PATH/hpeilo" ]; then
+	#move hepilo folder to nagios share directory
+	update_nagios_url_path $nagios_path
+fi
+
 local nagios_cfg_dir=`grep "^cfg_dir=$nagios_path" $nagios_cfg | \
 tail -n 1 | cut -d '=' -f 2`
 write_log "nagios_cfg_dir : $nagios_cfg_dir"
@@ -1193,6 +1380,18 @@ fi
 # Get the name of the nagios service: nagios or nagios3
 NagiosService=`find /etc/init.d/ -name "nagios*"  | xargs basename`
 }
+
+function update_nagios_url_path() {
+local nagios_share=
+
+if [ -f "$1/cgi.cfg" ]; then
+	nagios_share=`cat $1/cgi.cfg | grep -i "physical_html_path=" | cut -d '=' -f 2`
+	if [ -d "$nagios_share/hpeilo" ]; then
+		`rm -rf $nagios_share/hpeilo`
+	fi
+	`cp $NAGIOS_ILO_PLUGINS_PATH/hpeilo $nagios_share -rf`
+fi
+}	
 
 # Start here
 if [[ $EUID -ne 0 ]]; then
@@ -1289,6 +1488,12 @@ ActiveDiscMode()
 		exit 1
 	fi
 
+	CurlBin=`which curl 2>/dev/null`
+
+        if [ $? -ne 0 ]; then
+                echo "[Error]: Cannot find curl utility. You need to install curl"
+                exit 1
+        fi
 	check_nmap_version "$NmapBin"	
 	if [ ${#IfName[@]} -ne 0 ]; then
 		useNetInterface=1
@@ -1304,7 +1509,8 @@ ActiveDiscMode()
 }
 
 #remove lock file if exist 
-rm -f $LockFile
+#fix QXCR1001454803 -- [NIAP] nagios daemon start error since redundant host find can't be configured
+#rm -f $LockFile
 
 # Check the discovery mode
 check_mode $mode
@@ -1343,9 +1549,7 @@ case $mode in
 	# is <UNKNOWN>.
 	# 	Example for the protocol variable:
 	#		UDP: [16.153.112.187]:58240->[16.153.113.255]
-	if [ "$IloIP" = "<UNKNOWN>" ]; then
-		IloIP=`echo $protocol | cut -d '[' -f 2 | cut -d ']' -f 1`
-	fi
+	IloIP=`echo $protocol | cut -d '[' -f 2 | cut -d ']' -f 1`
 
 	check_ilo_device $IloIP
 
@@ -1356,6 +1560,7 @@ case $mode in
 		# reload nagios configuration files
 		`service $NagiosService reload > /dev/null`
 	fi
+	exit 0
 
 	;;
 	$ConfigDisc)
diff --git a/scripts/nagios_hpeilo_traps.in b/scripts/nagios_hpeilo_traps.in
--- a/scripts/nagios_hpeilo_traps.in
+++ b/scripts/nagios_hpeilo_traps.in
@@ -1,10 +1,10 @@
 #!/bin/bash
 #
-#  nagios_hpilo_traps -- The script aims to collect the SNMP traps 
+#  nagios_hpeilo_traps -- The script aims to collect the SNMP traps 
 #			 received from HP ProLiant Server and to 
 #			 update the corresponding status in real-time
 #	        
-#  (C) Copyright [2015] Hewlett-Packard Development Company, L.P.
+#  (C) Copyright [2015] Hewlett-Packard Enterprise Development Company, L.P.
 #
 #  This program is free software; you can redistribute it and/or modify 
 #  it under the terms of version 2 of the GNU General Public License as 
@@ -27,12 +27,11 @@
 prefix=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
 NagiosLibexec="${prefix}"
-NagiosHpiloEngine="nagios_hpilo_engine"
+NagiosHpiloEngine="nagios_hpeilo_engine"
 
-HpiloLogFile="/var/log/nagios_hpilo_traps.log"
-HpiloSnmpComm="public" # hpilo ilo community string
-HpiloServices=("System Status" "Fans" "Memory" "Network" "Power Supplies"\
-		 "Processors" "Storage" "Temperatures")
+HpiloLogFile="/var/log/nagios_hpeilo_traps.log"
+HpiloSnmpComm="public" # hpeilo ilo community string
+HpiloServices=("System Status" "Fans" "Memory" "Network" "Power Supplies" "Processors" "Storage" "Temperatures")
 
 SnmpTrapOid="iso.3.6.1.6.3.1.1.4.1.0"
 
@@ -155,6 +154,98 @@ function update_hlth_status () {
 		
 
 }
+
+# argument 1 ($1): the iLO IP  
+# argument 2 ($2): the iLO IP  RO community string
+function update_hlth_status_from_status_array () {
+	local nagios_cfg_file=$(get_nagios_cfg_file)
+	local oid_idx=0
+	local curr_oid_idx=$3
+	local curr_oid_idx=$((curr_oid_idx-1))
+	local curr_odi_status=
+	local curr_oid_disc=
+	nagios_service_status=0
+	local hlth_array_count=0
+	write_log "$nagios_cfg_file"
+
+	NagiosCmdFile=`grep -r command_file $nagios_cfg_file | \
+		awk -F = '{print $2}'`
+
+
+	# The oid_idx must be increased by 1 since the oid index of the 
+	# NagiosHpiloEngine is started from 1 rather than 0. 
+	write_log "$NagiosLibexec/$NagiosHpiloEngine -H $1 -C $2 -o $((oid_idx))" 
+	output=`$NagiosLibexec/$NagiosHpiloEngine -H $1 -C $2 -o $((oid_idx))`
+	nagios_service_status=$?
+	write_log "${HpiloServices[0]} nagios_service_status : $nagios_service_status - $output"
+	IFS=';' read -a hlth_status_array <<< "$output"	
+	hlth_array_count=${#hlth_status_array[@]}
+	for ((xy=0;xy<${#HpiloServices[@]};xy++));do
+		service_key=${HpiloServices[$xy]}
+		case $service_key in
+			"System Status") service_index=0 ;;
+			"Fans") service_index=4 ;;
+			"Memory") service_index=3 ;;
+			"Network") service_index=14 ;;
+			"Power Supplies") service_index=6 ;;
+			"Processors") service_index=2 ;;
+			"Storage") service_index=9 ;;
+			"Temperatures") service_index=5 ;;
+			*) ;; 
+		esac
+
+		write_log "hlth_array_count : $hlth_array_count"
+		if [ $hlth_array_count = 1 ]; then
+			status_key=${hlth_status_array[0]}
+			status_value=3
+			write_log "status_key : $status_key"
+		else
+			status_key=${hlth_status_array[$service_index]}
+			case $status_key in
+				"OK") status_value=0 ;;
+				"Degraded") status_value=1 ;; 
+				"Failed") status_value=2 ;;
+				"NA" | "Other") status_value=3 ;;
+				*) ;;
+			esac
+		fi
+
+		if [ "$status_value" == "1" ] || [ "$status_value" == "2" ]; then
+			case "$xy" in
+				[1] | [4] | [6])
+					status_key=`$NagiosLibexec/$NagiosHpiloEngine -H $1 -C $2 -o $((xy+1))`
+					nagios_service_status=$?
+					;;
+				*)
+					;;
+			esac
+		elif [ "$status_value" == "3" ]; then
+			case "$xy" in
+				3)
+					status_key="Other: Probable Cause might be AMS service is not installed or started on host OS"
+				;;
+				4)
+					status_key="Other: Verify status on OA for Power Supplies of blade server" 
+				;;
+				*)
+				;;
+ 			esac
+		fi
+		if [ $curr_oid_idx = $xy ]; then
+			curr_odi_status=$status_value
+			curr_oid_disc="$status_key"
+			continue
+		fi
+		nagios_passive_check "$1" "${HpiloServices[$xy]}" "$status_value" "$status_key"
+		sleep 0.001
+	done
+	output=$curr_oid_disc
+	nagios_service_status=$curr_odi_status
+	write_log "5. $1 ${HpiloServices[0]} $nagios_service_status $output "
+
+}
+
+
 # $1: file name
 # $2: search pattern
 function search_string() {
@@ -166,26 +257,75 @@ fi
 echo $str
 }
 
-read IloIP 
-read protocol
+#start here
 
-# Get the iLO trap ID 
-while read oid val
-do
-	if [ "$oid" = "$SnmpTrapOid" ]; then
-		t
-		# get the iLO trap ID
-		IloTrapNumber=`echo $val | awk -F . '{print $NF}'`
-		break;
-	fi
+	VerboseMode=0
+	ActiveMode=0
+	
+
+# parse the arguments
+while [ "x$1" != "x" ]; do
+	option=$1
+
+	case $option in
+		-H)
+
+		# Get the Host IP
+		shift
+
+		host_ip=$1
+		;;
+
+		-C)
+		# Get the community string
+		shift
+		comm_str=$1
+
+		;;
+
+		-o)
+		# Get the OID
+		shift
+		oid_id=$1
+
+		;;
+
+		-v)
+		# enable verbose mode
+		VerboseMode=1
+		;;
+		
+		-A)
+		# Active mode: Get Health Status Array and Update to web page 
+		ActiveMode=1
+		;;
+		*)
+		echo "ERROR: unknown option $option"
+		
+		exit 1
+		;;
+
+	esac
+	shift
 done
 
-VerboseMode=0
-# verbose mode: write the log to the variable HpiloLogFile 
-if [ "$1" = "-v" ]
+
+if [ "$ActiveMode" = "0" ]
 then
-	VerboseMode=1
-fi
+
+	read IloIP 
+	read protocol
+
+# Get the iLO trap ID 
+	while read oid val
+	do
+		if [ "$oid" = "$SnmpTrapOid" ]; then
+			# get the iLO trap ID
+			IloTrapNumber=`echo $val | awk -F . '{print $NF}'`
+			break;
+		fi
+	done
+
 
 ServiceType=$(get_hlth_service_type $IloTrapNumber)
 
@@ -212,4 +352,15 @@ then
 
 	# update system health status
 	update_hlth_status $IloIP $IloTrapNumber "${HpiloServices[0]}"
+fi
+else
+
+	write_log "host_ip : $host_ip  comm_str: $comm_str  oid_idx: $oid_id"
+	#if [ "$oid_id" = "1" ]; then
+	write_log "Active Schedule Mode"
+		update_hlth_status_from_status_array $host_ip $comm_str $oid_id
+		printf "$output\n"
+		exit $nagios_service_status
+	#fi
+	
 fi
